// Role & permission model for the platform.
// Keep this data-driven so an admin could theoretically reconfigure it later
// (Section 3 / Section 40 of the spec).

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  OPS_ADMIN: 'OPS_ADMIN',
  FINANCE_ADMIN: 'FINANCE_ADMIN',
  CLUB_MANAGER: 'CLUB_MANAGER',
  COMMUNITY_ADMIN: 'COMMUNITY_ADMIN',
  MODERATOR: 'MODERATOR',
  PLAYER: 'PLAYER',
};

export const ROLE_LABELS = {
  SUPER_ADMIN: 'Super Admin',
  OPS_ADMIN: 'Operations Admin',
  FINANCE_ADMIN: 'Finance Admin',
  CLUB_MANAGER: 'Club Manager',
  COMMUNITY_ADMIN: 'Community Admin',
  MODERATOR: 'Moderator',
  PLAYER: 'Player',
};

// Permission keys grouped by module.
export const PERMISSIONS = {
  USERS_VIEW: 'USERS_VIEW',
  USERS_MANAGE: 'USERS_MANAGE',
  ROLES_MANAGE: 'ROLES_MANAGE',

  CLUBS_VIEW: 'CLUBS_VIEW',
  CLUBS_MANAGE: 'CLUBS_MANAGE',
  CLUBS_MANAGE_OWN: 'CLUBS_MANAGE_OWN',

  COURTS_MANAGE: 'COURTS_MANAGE',
  COURTS_MANAGE_OWN: 'COURTS_MANAGE_OWN',

  GAMES_VIEW_ALL: 'GAMES_VIEW_ALL',
  GAMES_MANAGE: 'GAMES_MANAGE',

  BOOKINGS_VIEW_ALL: 'BOOKINGS_VIEW_ALL',
  BOOKINGS_MANAGE: 'BOOKINGS_MANAGE',

  TOURNAMENTS_VIEW_ALL: 'TOURNAMENTS_VIEW_ALL',
  TOURNAMENTS_MANAGE: 'TOURNAMENTS_MANAGE',

  COMMUNITIES_VIEW_ALL: 'COMMUNITIES_VIEW_ALL',
  COMMUNITIES_MANAGE: 'COMMUNITIES_MANAGE',
  COMMUNITIES_MODERATE_OWN: 'COMMUNITIES_MODERATE_OWN',

  FINANCE_VIEW: 'FINANCE_VIEW',
  FINANCE_MANAGE: 'FINANCE_MANAGE',

  SUPPORT_VIEW: 'SUPPORT_VIEW',
  SUPPORT_MANAGE: 'SUPPORT_MANAGE',

  REPORTS_VIEW: 'REPORTS_VIEW',
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',
  AUDIT_VIEW: 'AUDIT_VIEW',

  RATING_OVERRIDE: 'RATING_OVERRIDE',
  RESULT_OVERRIDE: 'RESULT_OVERRIDE',

  ADMIN_PANEL_ACCESS: 'ADMIN_PANEL_ACCESS',
};

const ALL = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: ALL,
  [ROLES.OPS_ADMIN]: [
    PERMISSIONS.ADMIN_PANEL_ACCESS,
    PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.CLUBS_VIEW, PERMISSIONS.CLUBS_MANAGE,
    PERMISSIONS.COURTS_MANAGE,
    PERMISSIONS.GAMES_VIEW_ALL, PERMISSIONS.GAMES_MANAGE,
    PERMISSIONS.BOOKINGS_VIEW_ALL, PERMISSIONS.BOOKINGS_MANAGE,
    PERMISSIONS.TOURNAMENTS_VIEW_ALL, PERMISSIONS.TOURNAMENTS_MANAGE,
    PERMISSIONS.COMMUNITIES_VIEW_ALL, PERMISSIONS.COMMUNITIES_MANAGE,
    PERMISSIONS.SUPPORT_VIEW, PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.RESULT_OVERRIDE,
  ],
  [ROLES.FINANCE_ADMIN]: [
    PERMISSIONS.ADMIN_PANEL_ACCESS,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.BOOKINGS_VIEW_ALL,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [ROLES.CLUB_MANAGER]: [
    PERMISSIONS.ADMIN_PANEL_ACCESS,
    PERMISSIONS.CLUBS_MANAGE_OWN,
    PERMISSIONS.COURTS_MANAGE_OWN,
    PERMISSIONS.GAMES_MANAGE,
    PERMISSIONS.BOOKINGS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [ROLES.COMMUNITY_ADMIN]: [
    PERMISSIONS.ADMIN_PANEL_ACCESS,
    PERMISSIONS.COMMUNITIES_MODERATE_OWN,
  ],
  [ROLES.MODERATOR]: [
    PERMISSIONS.ADMIN_PANEL_ACCESS,
    PERMISSIONS.COMMUNITIES_MODERATE_OWN,
  ],
  [ROLES.PLAYER]: [],
};

export function can(role, permission) {
  if (!role) return false;
  const perms = ROLE_PERMISSIONS[role] || [];
  return perms.includes(permission);
}

export function isAdminRole(role) {
  return role && role !== ROLES.PLAYER;
}

// Which admin nav sections a role should see.
export function adminSectionsFor(role) {
  const sections = [];
  if (can(role, PERMISSIONS.ADMIN_PANEL_ACCESS)) sections.push('dashboard');
  if (can(role, PERMISSIONS.USERS_VIEW) || role === ROLES.SUPER_ADMIN) sections.push('users');
  if (can(role, PERMISSIONS.CLUBS_VIEW) || can(role, PERMISSIONS.CLUBS_MANAGE_OWN)) sections.push('clubs');
  if (can(role, PERMISSIONS.GAMES_VIEW_ALL)) sections.push('games');
  if (can(role, PERMISSIONS.BOOKINGS_VIEW_ALL) || can(role, PERMISSIONS.BOOKINGS_MANAGE)) sections.push('bookings');
  if (can(role, PERMISSIONS.TOURNAMENTS_VIEW_ALL)) sections.push('tournaments');
  if (can(role, PERMISSIONS.COMMUNITIES_VIEW_ALL) || can(role, PERMISSIONS.COMMUNITIES_MODERATE_OWN)) sections.push('communities');
  if (can(role, PERMISSIONS.FINANCE_VIEW)) sections.push('finance');
  if (can(role, PERMISSIONS.SUPPORT_VIEW)) sections.push('support');
  if (can(role, PERMISSIONS.REPORTS_VIEW)) sections.push('reports');
  if (can(role, PERMISSIONS.SETTINGS_MANAGE)) sections.push('settings');
  if (can(role, PERMISSIONS.AUDIT_VIEW)) sections.push('audit');
  if (can(role, PERMISSIONS.ROLES_MANAGE)) sections.push('roles');
  return sections;
}
