// Explicit state machines (Spec Section 57). Every module transitions through
// these graphs instead of ad-hoc booleans. `assertTransition` throws a
// descriptive error if the UI ever attempts an illegal transition, which is
// how we keep the "connected app" invariants honest during development.

export const GAME_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  OPEN_FOR_JOINING: 'OPEN_FOR_JOINING',
  FULL: 'FULL',
  LOCKED: 'LOCKED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const GAME_TRANSITIONS = {
  DRAFT: ['PUBLISHED', 'CANCELLED'],
  PUBLISHED: ['OPEN_FOR_JOINING', 'CANCELLED'],
  OPEN_FOR_JOINING: ['FULL', 'LOCKED', 'IN_PROGRESS', 'CANCELLED'],
  FULL: ['OPEN_FOR_JOINING', 'LOCKED', 'IN_PROGRESS', 'CANCELLED'],
  LOCKED: ['IN_PROGRESS', 'CANCELLED'],
  IN_PROGRESS: ['COMPLETED', 'CANCELLED'],
  COMPLETED: [],
  CANCELLED: [],
};

export const BOOKING_STATUS = {
  AVAILABLE: 'AVAILABLE',
  HOLD: 'HOLD',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  CONFIRMED: 'CONFIRMED',
  CHECKED_IN: 'CHECKED_IN',
  COMPLETED: 'COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CANCEL_REQUESTED: 'CANCEL_REQUESTED',
  CANCELLED: 'CANCELLED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
};

export const BOOKING_TRANSITIONS = {
  AVAILABLE: ['HOLD'],
  HOLD: ['PAYMENT_PENDING', 'AVAILABLE'],
  PAYMENT_PENDING: ['CONFIRMED', 'PAYMENT_FAILED'],
  PAYMENT_FAILED: ['AVAILABLE', 'PAYMENT_PENDING'],
  CONFIRMED: ['CHECKED_IN', 'CANCEL_REQUESTED', 'COMPLETED'],
  CHECKED_IN: ['COMPLETED'],
  COMPLETED: [],
  CANCEL_REQUESTED: ['CANCELLED'],
  CANCELLED: ['REFUND_PENDING'],
  REFUND_PENDING: ['REFUNDED'],
  REFUNDED: [],
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
};

export const TOURNAMENT_STATUS = {
  DRAFT: 'DRAFT',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const TOURNAMENT_TRANSITIONS = {
  DRAFT: ['REGISTRATION_OPEN', 'CANCELLED'],
  REGISTRATION_OPEN: ['REGISTRATION_CLOSED', 'CANCELLED'],
  REGISTRATION_CLOSED: ['UPCOMING', 'CANCELLED'],
  UPCOMING: ['LIVE', 'CANCELLED'],
  LIVE: ['COMPLETED', 'CANCELLED'],
  COMPLETED: [],
  CANCELLED: [],
};

export const REGISTRATION_STATUS = {
  TEAM_PENDING: 'TEAM_PENDING',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  WITHDRAWN: 'WITHDRAWN',
  CANCELLED: 'CANCELLED',
};

export const MATCH_STATUS = {
  SCHEDULED: 'SCHEDULED',
  CHECKED_IN: 'CHECKED_IN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  WALKOVER: 'WALKOVER',
  CANCELLED: 'CANCELLED',
};

export const MATCH_TRANSITIONS = {
  SCHEDULED: ['CHECKED_IN', 'IN_PROGRESS', 'WALKOVER', 'CANCELLED'],
  CHECKED_IN: ['IN_PROGRESS', 'WALKOVER', 'CANCELLED'],
  IN_PROGRESS: ['COMPLETED', 'WALKOVER'],
  COMPLETED: [],
  WALKOVER: [],
  CANCELLED: [],
};

export const CLUB_STATUS = { ACTIVE: 'ACTIVE', PENDING: 'PENDING', SUSPENDED: 'SUSPENDED', CLOSED: 'CLOSED' };
export const COURT_STATUS = { AVAILABLE: 'AVAILABLE', BOOKED: 'BOOKED', MAINTENANCE: 'MAINTENANCE', BLOCKED: 'BLOCKED' };

export const COMMUNITY_MEMBER_STATUS = { PENDING: 'PENDING', ACTIVE: 'ACTIVE', BANNED: 'BANNED', REMOVED: 'REMOVED' };
export const COMMUNITY_ROLE = { OWNER: 'OWNER', ADMIN: 'ADMIN', MODERATOR: 'MODERATOR', MEMBER: 'MEMBER' };

export const EVENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  FULL: 'FULL',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const TICKET_STATUS = {
  NEW: 'NEW',
  ASSIGNED: 'ASSIGNED',
  INVESTIGATING: 'INVESTIGATING',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

export const TICKET_TRANSITIONS = {
  NEW: ['ASSIGNED', 'CLOSED'],
  ASSIGNED: ['INVESTIGATING', 'RESOLVED', 'CLOSED'],
  INVESTIGATING: ['RESOLVED', 'CLOSED'],
  RESOLVED: ['CLOSED', 'INVESTIGATING'],
  CLOSED: [],
};

export function canTransition(map, from, to) {
  if (from === to) return true;
  return Boolean(map[from] && map[from].includes(to));
}

export function assertTransition(map, from, to, label = 'entity') {
  if (!canTransition(map, from, to)) {
    throw new Error(`Illegal ${label} transition: ${from} → ${to}`);
  }
  return to;
}
